package tfg_uoc.dao;
// Generated 23-mar-2018 19:41:08 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
@SuppressWarnings("serial")
public class Factura implements java.io.Serializable {

	private Integer idFactura;
	private Clientes clientes;
	private Usuarioslogin usuarioslogin;
	private Date fecha;
	private Date fechaPago;
	private Date fechaEntrega;
	private int prendas;
	private int perchas;
	private float total;
	private boolean estado;
	private Set percheros = new HashSet(0);
	private Set userviciofacturas = new HashSet(0);
	private Set upercherofacturas = new HashSet(0);

	public Factura() {
	}

	public Factura(Clientes clientes, Usuarioslogin usuarioslogin, Date fecha, int prendas, int perchas, float total,
			boolean estado) {
		this.clientes = clientes;
		this.usuarioslogin = usuarioslogin;
		this.fecha = fecha;
		this.prendas = prendas;
		this.perchas = perchas;
		this.total = total;
		this.estado = estado;
	}
	
	public Factura(Clientes clientes, Usuarioslogin usuarioslogin, Date fecha, Date fechaPago, int prendas, int perchas, float total,
			boolean estado) {
		this.clientes = clientes;
		this.usuarioslogin = usuarioslogin;
		this.fecha = fecha;
		this.fechaPago = fechaPago;
		this.prendas = prendas;
		this.perchas = perchas;
		this.total = total;
		this.estado = estado;
	}

	public Factura(Clientes clientes, Usuarioslogin usuarioslogin, Date fecha, Date fechaPago, Date fechaEntrega,
			int prendas, int perchas, float total, boolean estado, Set percheros, Set userviciofacturas,
			Set upercherofacturas) {
		this.clientes = clientes;
		this.usuarioslogin = usuarioslogin;
		this.fecha = fecha;
		this.fechaPago = fechaPago;
		this.fechaEntrega = fechaEntrega;
		this.prendas = prendas;
		this.perchas = perchas;
		this.total = total;
		this.estado = estado;
		this.percheros = percheros;
		this.userviciofacturas = userviciofacturas;
		this.upercherofacturas = upercherofacturas;
	}

	public Integer getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(Integer id) {
		this.idFactura = id;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Usuarioslogin getUsuarioslogin() {
		return this.usuarioslogin;
	}

	public void setUsuarioslogin(Usuarioslogin usuarioslogin) {
		this.usuarioslogin = usuarioslogin;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	public int getPrendas() {
		return this.prendas;
	}

	public void setPrendas(int prendas) {
		this.prendas = prendas;
	}

	public int getPerchas() {
		return this.perchas;
	}

	public void setPerchas(int perchas) {
		this.perchas = perchas;
	}

	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public Set getPercheros() {
		return this.percheros;
	}

	public void setPercheros(Set percheros) {
		this.percheros = percheros;
	}

	public Set getUserviciofacturas() {
		return this.userviciofacturas;
	}

	public void setUserviciofacturas(Set userviciofacturas) {
		this.userviciofacturas = userviciofacturas;
	}

	public Set getUpercherofacturas() {
		return this.upercherofacturas;
	}

	public void setUpercherofacturas(Set upercherofacturas) {
		this.upercherofacturas = upercherofacturas;
	}

}
