package tfg_uoc.dao;
// Generated 23-mar-2018 19:41:08 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario implements java.io.Serializable {

	private int idTipo;
	private String tipo;
	private String descripcion;
	private Set usuarioslogins = new HashSet(0);

	public Tipousuario() {
	}

	public Tipousuario(int idTipo, String tipo) {
		this.idTipo = idTipo;
		this.tipo = tipo;
	}

	public Tipousuario(int idTipo, String tipo, String descripcion, Set usuarioslogins) {
		this.idTipo = idTipo;
		this.tipo = tipo;
		this.descripcion = descripcion;
		this.usuarioslogins = usuarioslogins;
	}

	public int getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(int idTipo) {
		this.idTipo = idTipo;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getUsuarioslogins() {
		return this.usuarioslogins;
	}

	public void setUsuarioslogins(Set usuarioslogins) {
		this.usuarioslogins = usuarioslogins;
	}

}
