package tfg_uoc.dao;
// Generated 23-mar-2018 19:41:08 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarioslogin generated by hbm2java
 */
public class Usuarioslogin implements java.io.Serializable {

	private String usuario;
	private Tipousuario tipousuario;
	private String nombre;
	private String pass;
	private Set facturas = new HashSet(0);

	public Usuarioslogin() {
	}

	public Usuarioslogin(String usuario, Tipousuario tipousuario, String nombre, String pass) {
		this.usuario = usuario;
		this.tipousuario = tipousuario;
		this.nombre = nombre;
		this.pass = pass;
	}

	public Usuarioslogin(String usuario, Tipousuario tipousuario, String nombre, String pass, Set facturas) {
		this.usuario = usuario;
		this.tipousuario = tipousuario;
		this.nombre = nombre;
		this.pass = pass;
		this.facturas = facturas;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Tipousuario getTipousuario() {
		return this.tipousuario;
	}

	public void setTipousuario(Tipousuario tipousuario) {
		this.tipousuario = tipousuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public Set getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set facturas) {
		this.facturas = facturas;
	}

}
